meta_product_name: "BandMates"
meta_title: "BandMates - Bringing Musicians Together, Wherever"
meta_description: "A social networking platform for musicians and music lovers. A place to find your missing bandmate and meet music lovers."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
